### ISSUE TITLE
out of memory

### ISSUE THREAD

**Issue by jackgreentemp** [gbaldera/TiTouchGallery#12]
I have issues of out of memory when open jpg image, how to solve this?

[INFO]  I/dalvikvm-heap: Forcing collection of SoftReferences for 31961104-byte allocation
[ERROR] E/dalvikvm-heap: Out of memory on a 31961104-byte allocation.
[INFO]  dalvikvm: "AsyncTask #7" prio=5 tid=34 RUNNABLE
[INFO]  dalvikvm:   | group="main" sCount=0 dsCount=0 obj=0x449d4980 self=0x79dc2b10
[INFO]  dalvikvm:   | sysTid=16380 nice=10 sched=0/0 cgrp=apps/bg_non_interactive handle=2042594704
[INFO]  dalvikvm:   | state=R schedstat=( 125096816 17374656 32 ) utm=11 stm=1 core=4
[INFO]  dalvikvm:   at android.graphics.BitmapFactory.nativeDecodeStream(Native Method)
[INFO]  dalvikvm:   at android.graphics.BitmapFactory.decodeStreamInternal(BitmapFactory.java:632)
[INFO]  dalvikvm:   at android.graphics.BitmapFactory.decodeStream(BitmapFactory.java:608)
[INFO]  dalvikvm:   at android.graphics.BitmapFactory.decodeStream(BitmapFactory.java:646)
[INFO]  dalvikvm:   at ru.truba.touchgallery.TouchView.UrlTouchImageView$ImageLoadTask.doInBackground(UrlTouchImageView.java:104)
[INFO]  dalvikvm:   at ru.truba.touchgallery.TouchView.UrlTouchImageView$ImageLoadTask.doInBackground(UrlTouchImageView.java:82)
[INFO]  dalvikvm:   at android.os.AsyncTask$2.call(AsyncTask.java:288)
[INFO]  dalvikvm:   at java.util.concurrent.FutureTask.run(FutureTask.java:237)
[INFO]  dalvikvm:   at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:231)
[INFO]  dalvikvm:   at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
[INFO]  dalvikvm:   at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
[INFO]  dalvikvm:   at java.lang.Thread.run(Thread.java:841)
[INFO]  dalvikvm:
[WARN]  dalvikvm: threadid=34: thread exiting with uncaught exception (group=0x41638c68)

**Comment by zmcNotafraid** [comment]
I got this error too
